feat: added user page
dscnitrourkela/project-raisin pull request #65
Opened 2023-09-26 06:33 UTC by starkjay21

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-09-26 06:40 UTC, starkjay21 commented
@Shurtu-gal Please review

2023-09-27 10:24 UTC, Shurtu-gal requested changes

2023-09-27 10:24 UTC, Shurtu-gal commented on src/components/User/styles.js
> +export const RegEventClubname = styled.p`
Use typography instead of directly putting sizes.

2023-09-27 19:06 UTC, Shurtu-gal approved these changes
LGTM 🤖

2023-09-27 19:06 UTC, merged