feat: added navbar
dscnitrourkela/project-raisin pull request #66
Opened 2023-09-26 18:03 UTC by SirSimon162

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description

Please describe your pull request.
Added new navbar

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-09-26 18:07 UTC, SirSimon162 commented
@Shurtu-gal please review

2023-09-27 09:44 UTC, Shurtu-gal requested changes

2023-09-27 09:44 UTC, Shurtu-gal commented on src/components/marginals/Navbar/styles.jsx
> +      background: linear-gradient(88.29deg, #ffb8ff 1.56%, #b9cdff 94.54%);
Use the variable declared in global CSS.
`
background: var(--brand-gradient);
`

2023-09-27 09:44 UTC, Shurtu-gal commented on src/components/marginals/Navbar/DesktopNav.jsx
> +            <AuthButton />
Delete the authButton and use https://github.com/dscnitrourkela/project-raisin/blob/main/src/components/shared/Button.jsx with an outline prop.

2023-09-27 12:40 UTC, Shurtu-gal approved these changes
LGTM 🚀

2023-09-27 12:40 UTC, merged