feat: add About, Events, Footer section & fix: minor typography issues
dscnitrourkela/project-raisin pull request #8
Opened 2022-10-18 06:52 UTC by ORKO06

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Added About Component in shared as it can be reused.
Added Event Category Section and Footer Component
Fixed minor typography issues and import error.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-10-18 07:10 UTC, abhibhaw commented
Footer needs a bit more space at the bottom. For events sec don't scroll full thing, keep title fixed and scroll the cards

2022-10-18 07:17 UTC, abhibhaw requested changes

2022-10-18 07:17 UTC, abhibhaw commented on src/pages/playground.js
> +import Footer from '../components/marginals/Footer/Footer';
Line 2 @ratnakar5938 is importing everything from the component module, you're importing relative to the absolute path. Please fix it to one format.

2022-10-18 11:58 UTC, riteshsp2000 commented
small changes here and there...
- make the entire card clickable
- make the entire faq clickable
- add some border radius to the about section video
- on mobile page add some gap between the sections in footer

2022-10-23 09:47 UTC, riteshsp2000 approved these changes

2022-10-23 10:00 UTC, abhibhaw approved these changes
LGTM

2022-10-23 10:00 UTC, merged