Content-Updates-1
dscnitrourkela/project-raisin pull request #93
Opened 2023-10-13 12:28 UTC by anmol5936

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-10-13 14:17 UTC, Shurtu-gal commented
TODO:- 
- [ ] Sponsors
- [ ] About US
- [x] FAQ
- [ ] EventPage ( Photos )
- [ ] Footer
- [ ] Payment ( Contact and terms and conditions )

@starkjay21 @anmol5936

2023-10-13 14:30 UTC, starkjay21 requested changes, later dismissed
follow the commit message convention

2023-10-13 14:30 UTC, starkjay21 commented on config/content/FAQ.js
>        id: 8,
Remove this, it is repeated

2023-10-13 14:30 UTC, starkjay21 commented on config/content/FAQ.js
> +        'With our unrivalled ability to host such technical fests' +
add a space at the end of string

2023-10-13 14:30 UTC, starkjay21 commented on config/content/FAQ.js
> +        'All science and technology enthusiasts currently' +
add a space after end of string

2023-10-14 10:30 UTC, Shurtu-gal approved these changes
LGTM 🤖

2023-10-14 10:31 UTC, merged